version: "3.8"
services:
  zookeeper:
    image: debezium/zookeeper:1.6
    container_name: cqrswithcdc-zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:1.6
    container_name: cqrswithcdc-kafka
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  connect:
    image: debezium/connect:1.6
    container_name: cqrswithcdc-connect
    environment:
      GROUP_ID: "cqrswithcdc"
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
      - db

  consumers:
    build:
      dockerfile: CQRSwithCDC.Read/Dockerfile
      context: .
    container_name: cqrswithcdc-consumers

  db:
    build:
      dockerfile: Dockerfile.sqlserver
      context: .
    container_name: cqrswithcdc-db
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - 1433:1433
