version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment: 
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433

